version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###
